/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Views;

import UI.Controllers.mainFrameController;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import types.Grammar;

/**
 *
 * @author Camilo
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }
    Grammar grammar,loadedGrammar;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GeneradorLex = new java.awt.TextArea();
        jToolBar2 = new javax.swing.JToolBar();
        Open = new javax.swing.JButton();
        RunAnalisis = new javax.swing.JButton();
        saveGrammarButon = new javax.swing.JButton();
        loadGrammarButton = new javax.swing.JButton();
        Results = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jToolBar2.setRollover(true);

        Open.setText("Abrir");
        Open.setFocusable(false);
        Open.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Open.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        jToolBar2.add(Open);

        RunAnalisis.setText("Crear Analizador");
        RunAnalisis.setFocusable(false);
        RunAnalisis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RunAnalisis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RunAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunAnalisisActionPerformed(evt);
            }
        });
        jToolBar2.add(RunAnalisis);

        saveGrammarButon.setText("Guardar Analizador");
        saveGrammarButon.setFocusable(false);
        saveGrammarButon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveGrammarButon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveGrammarButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGrammarButonActionPerformed(evt);
            }
        });
        jToolBar2.add(saveGrammarButon);

        loadGrammarButton.setText("Cargar Analizador");
        loadGrammarButton.setFocusable(false);
        loadGrammarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loadGrammarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loadGrammarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGrammarButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(loadGrammarButton);

        Results.setEditable(false);
        Results.setEnabled(false);
        Results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GeneradorLex, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeneradorLex, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunAnalisisActionPerformed
        //String[] lines = GeneradorLex.getText().split("\n");
        mainFrameController controller = new mainFrameController();
        grammar = controller.generateGrammar(GeneradorLex.getText());
        Results.setText(controller.getMessage());
    }//GEN-LAST:event_RunAnalisisActionPerformed

    private void ResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultsActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenActionPerformed

    private void saveGrammarButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGrammarButonActionPerformed
        // TODO add your handling code here:
        if(grammar!=null)
            try{
                JFileChooser saveWindow = new JFileChooser();
                saveWindow.showSaveDialog(this);
                File file =saveWindow.getSelectedFile();
                if(file!=null)
                    mainFrameController.saveGrammar(file,grammar);
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        else
            JOptionPane.showMessageDialog(null,"Debe crear el analizador primero",
           "Advertencia",JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_saveGrammarButonActionPerformed

    private void loadGrammarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGrammarButtonActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser loadWindow = new JFileChooser();
            loadWindow.showOpenDialog(this);
            File file = loadWindow.getSelectedFile();
            if(file!=null)
                loadedGrammar = mainFrameController.loadGrammar(file);
            if(loadedGrammar!=null)
                new LexAnalyzerFrame(loadedGrammar).setVisible(true);
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_loadGrammarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea GeneradorLex;
    private javax.swing.JButton Open;
    private java.awt.TextField Results;
    private javax.swing.JButton RunAnalisis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton loadGrammarButton;
    private javax.swing.JButton saveGrammarButon;
    // End of variables declaration//GEN-END:variables
}
